spring:
  application:
    name: ms-users
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  flyway:
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true
    driver-class-name: org.postgresql.Driver
    connect-retries: 3

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.support: DEBUG
    org.springframework.jdbc.datasource: DEBUG

server:
  port: ${SERVER_PORT:8080}

api:
  security:
    token:
      secret: ${JWT_SECRET:123456789}
      issuer: ${JWT_ISSUER:ms-users}
      expiration-hours: ${JWT_EXPIRATION_HOURS:1}